class Event < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :user
  belongs_to :project
  belongs_to :source, polymorphic: true
  # validations ...............................................................
  validates :action, presence: true
  validates :user, presence: true
  # callbacks .................................................................
  # after_touch :touch_all_variants
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  # private
end
