class Project < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  belongs_to :team, inverse_of: :project
  has_many :accesses, dependent: :destroy, inverse_of: :project
  has_many :users, through: :accesses
  # validations ...............................................................
  validates_presence_of :name
  validates_uniqueness_of :name, scope: :team_id
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  # private
end
