class User < ActiveRecord::Base
  # extends ...................................................................
  # includes ..................................................................
  # relationships .............................................................
  has_many :memberships, dependent: :destroy
  has_many :teams, through: :memberships
  has_many :accesses, dependent: :destroy, inverse_of: :user
  has_many :projects, through: :accesses
  # validations ...............................................................
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  # callbacks .................................................................
  # after_touch :touch_all_variants
  # scopes ....................................................................
  # additional config (i.e. accepts_nested_attribute_for etc...) ..............
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
  # private
end
